### PR TITLE
feat: password change

### PR DESCRIPTION
**Pull request by CuriouzK0d3r**
### Description of PR

Added support for password strength check
What component(s) does this PR affect?

  - [x] Back-End (Node.js, Next.js)
  - [x] Front-End (React.js)
  - [x] Theming (CSS, React theme)
  - [ ] Build System
  - [ ] Docs
  
  
  
  Does the PR require changes on other components? If yes, please mark the components:
  
  - [ ] Back-End (Node.js, Next.js)
  - [ ] Front-End (React.js)
  - [ ] Theming (CSS, React theme)
  - [ ] Build System
  - [ ] Docs
  
  
  
### Related Issue
  
  
  
  
  
  
  Resolves #
  
### Type
  
  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to change)
  - [ ] Docs update
  - [ ] None of the above
  
  
  
### Checklist:
  
  - [ ] I have read the **[contributing guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
  - [ ] This change requires a change in the documentation.
  - [ ] I have updated the documentation accordingly.
  >)`>>>)>

### CODE REVIEW

**Review by vkotronis — COMMENTED** [review]
LGTM, just fix pending tests and then we can proceed. Cool Alex!
Btw does this affect the current default pass behavior we have? I.e., for demo installations with admin will login fail (`admin1234`)?

**Comment by CuriouzK0d3r** [comment]
> LGTM, just fix pending tests and then we can proceed. Cool Alex!
> Btw does this affect the current default pass behavior we have? I.e., for demo installations with admin will login fail (`admin1234`)?

It is not cool at all, the library is buggy and this pr took me almost a whole day 😂

It won't be affected directly but we should change it I think!

**Comment by CuriouzK0d3r** [comment]
> > LGTM, just fix pending tests and then we can proceed. Cool Alex!
> > Btw does this affect the current default pass behavior we have? I.e., for demo installations with admin will login fail (`admin1234`)?
> 
> It is not cool at all, the library is buggy and this pr took me almost a whole day 😂
> 
> It won't be affected directly but we should change it I think!

I fixed the tests and changed the default pass!

**Review by vkotronis — APPROVED** [review]
LGTM, nice work @CuriouzK0d3r

**Pull request merged**
