### PR TITLE
fix: LDAP button is hidden when no LDAP service is being used

### PR DESCRIPTION
**Pull request by CuriouzK0d3r**
### Description of PR

What component(s) does this PR affect?

  - [x] Back-End (Node.js, Next.js)
  - [x] Front-End (React.js)
  - [ ] Theming (CSS, React theme)
  - [ ] Build System
  - [ ] Docs
  
  
  
  Does the PR require changes on other components? If yes, please mark the components:
  
  - [ ] Back-End (Node.js, Next.js)
  - [ ] Front-End (React.js)
  - [ ] Theming (CSS, React theme)
  - [ ] Build System
  - [ ] Docs
  
  
  
### Related Issue
  
  
  
  
  
  
  Resolves #
  
### Type
  
  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to change)
  - [ ] Docs update
  - [ ] None of the above
  
  
  
### Checklist:
  
  - [ ] I have read the **[contributing guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
  - [ ] This change requires a change in the documentation.
  - [ ] I have updated the documentation accordingly.
  >)`>>>)>

### CODE REVIEW

**Review by vkotronis — COMMENTED** [review]
@CuriouzK0d3r LGTM, have you tested with a test LDAP server and without? Can you log-in fine using the test LDAP service we have? If you deactivate it is the button hidden?

**Comment by vkotronis** [comment]
> @CuriouzK0d3r LGTM, have you tested with a test LDAP server and without? Can you log-in fine using the test LDAP service we have? If you deactivate it is the button hidden?

Follow-up: tests seem to fail https://github.com/FORTH-ICS-INSPIRE/artemis-web/runs/4874427162?check_suite_focus=true so probably this requires some debugging before approval. Could you double-check?

**Comment by CuriouzK0d3r** [comment]
> @CuriouzK0d3r LGTM, have you tested with a test LDAP server and without? Can you log-in fine using the test LDAP service we have? If you deactivate it is the button hidden?

Yeah I tested! Sorry though, I intended the pr to be a  draft :(

**Review by vkotronis — APPROVED** [review]
LGTM

**Pull request merged**
